### ISSUE TITLE
尝试使用2.2.5和2.3.0版本 均出现Mbp m2 无法导入txt/pdf文件生成词库

### ISSUE THREAD

**Issue by kssdxw** [tangshimin/MuJing#59]
具体表现为弹窗中显示共xxxx个词，但弹窗消失后，未出现任何词，显示共0词。

**Comment by kssdxw** [comment]
*弹窗指的是点击开始后的旋转进度条，每次重新打开的第一次导入旋转进度条会显示有多少词，第二次的时候就不会显示了。

**Comment by kssdxw** [comment]
尝试从命令行启动后看到报错：

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: ecdict)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at data.Dictionary.queryList(Dictionary.kt:104)
	at ui.dialog.GenerateVocabularyDialogKt.readDocument(GenerateVocabularyDialog.kt:2676)
	at ui.dialog.GenerateVocabularyDialogKt$GenerateVocabularyDialog$2$analysis$1$1.invokeSuspend(GenerateVocabularyDialog.kt:561)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
`

**Comment by tangshimin** [comment]
macOS 版最近几个版本使用 Github/Action 打包的，打包脚本忘了解压缩词典文件。
词典文件在   app>resources>dictionary 文件夹里面，把这个 7z 文件解压缩应该就可以了

**Comment by kssdxw** [comment]
感谢！！！搞定了，有一块是如果之前打开过软件，会生成一个ecdict.db的空文件，解压后记得把这个空文件删了，用压缩包里的ecdict.db。
